import json

with open('src/data/jobDetails.json', 'r', encoding='utf-8') as f:
    details = json.load(f)

added_keys = [
    'rars-chintapalle-teaching-associate-and-teachi-recruitment-2026',
    'homi-bhabha-cancer-hospital-r-medical-officer-recruitment-2026',
    'andhra-pradesh-capital-region-assistant-manager-legal-recruitment-2026',
    'ship-building-centre-visakhap-construction-assistant-a-caa-c-recruitment-2026',
    'flood-and-river-erosion-manag-it-assistant-accounts-assista-recruitment-2026',
    'tezpur-university-junior-research-fellow-jrf-s-recruitment-2026',
    'tezpur-university-assistant-professor-contract-recruitment-2026',
    'bihar-state-food-civil-suppli-accountant-lower-grade-clerk-recruitment-2026',
    'panjab-university-guest-faculty-recruitment-2026',
    'cmho-balodabazar-nursing-offic-nursing-officer-attendant-and-recruitment-2026',
    'bastar-district-subject-expert-part-time-musi-recruitment-2026',
    'container-corporation-of-indi-management-trainee-and-assist-recruitment-2026',
    'solar-energy-corporation-of-in-general-manager-accounts-offi-recruitment-2026',
    'delhi-university-south-campus-junior-research-fellow-recruitment-2026',
    'ernet-india-project-engineer-project-mana-recruitment-2026',
    'delhi-pollution-control-commi-environmental-engineer-assist-recruitment-2026',
    'central-electricity-regulatory-joint-chief-deputy-chief-and-recruitment-2026',
    'ernet-india-administrative-assistant-procu-recruitment-2026',
    'supreme-court-of-india-assistant-registrar-recruitment-2026',
    'national-highways-authority-of-manager-senior-librarian-info-recruitment-2026',
    'ministry-of-environment-fores-scientific-consultant-grade-i-recruitment-2026',
    'all-india-institute-of-medica-data-entry-operator-project-n-recruitment-2026',
    'jawaharlal-nehru-university-j-advocate-recruitment-2026',
    'warehousing-development-and-re-consultant-recruitment-2026',
    'national-forensic-sciences-un-visiting-medical-consultant-p-recruitment-2026',
    'employees-state-insurance-cor-teaching-faculty-recruitment-2026',
    'indian-institute-of-informati-assistant-professor-grade-ii-recruitment-2026',
    'sardar-vallabhbhai-national-i-teaching-assistant-recruitment-2026',
    'bhavnagar-municipal-corporati-mphw-executive-engineer-and-m-recruitment-2026',
    'engineers-india-limited-eil-associate-engineer-recruitment-2026',
    'bric-national-brain-research-c-project-technical-support-i-recruitment-2026',
    'national-brain-research-centre-research-assistant-iii-recruitment-2026',
    'national-brain-research-centre-account-assistant-recruitment-2026',
    'rites-limited-engineer-recruitment-2026',
    'all-india-institute-of-medica-project-technical-support-iii-recruitment-2026',
    'iit-ism-dhanbad-project-associate-recruitment-2026',
    'district-mineral-foundation-tr-specialist-anaesthesiologist-recruitment-2026',
    'drdo-defence-institute-of-bio-research-associate-junior-res-recruitment-2026',
    'chikkaballapur-district-community-health-officer-cho-recruitment-2026',
    'csir-central-food-technologic-senior-project-associate-recruitment-2026',
    'karnataka-residential-educati-social-welfare-residential-sc-recruitment-2026',
    'kerala-academy-for-skills-exc-manager-recruitment-2026',
    'indira-gandhi-national-tribal-project-assistant-recruitment-2026',
    'ordnance-factory-katni-labour-welfare-officer-recruitment-2026',
    'indira-gandhi-national-tribal-company-secretary-cs-firm-recruitment-2026',
    'advanced-centre-for-treatment-research-associate-junior-res-recruitment-2026',
    'csir-national-environmental-e-project-associate-i-recruitment-2026',
    'icar-central-institute-for-re-business-manager-recruitment-2026',
    'advanced-centre-for-treatment-scientific-assistant-recruitment-2026',
    'advanced-centre-for-treatment-attendant-recruitment-2026',
    'rashtriya-chemicals-and-ferti-management-trainee-recruitment-2026',
    'eklavya-model-residential-sch-driver-cook-and-more-recruitment-2026',
    'north-eastern-indira-gandhi-r-senior-resident-doctor-recruitment-2026',
    'odisha-adarsha-vidyalaya-bhal-warden-assistant-cook-and-mo-recruitment-2026',
    'odisha-adarsha-vidyalaya-mayur-support-staff-recruitment-2026',
    'odisha-adarsha-vidyalaya-shirs-support-staff-recruitment-2026',
    'odisha-adarsha-vidyalaya-morad-support-staff-for-boys-hostel-recruitment-2026',
    'gopabandhu-science-college-guest-faculty-recruitment-2026',
    'odisha-adarsha-vidyalaya-garud-hostel-support-staff-recruitment-2026',
    'jawaharlal-institute-of-postgr-project-technical-assistant-recruitment-2026',
    'guru-gobind-singh-medical-coll-project-technical-support-iii-recruitment-2026',
    'district-health-society-tiruch-driver-and-microbiologist-recruitment-2026',
    'one-stop-centre-erode-senior-counsellor-recruitment-2026',
    'tamilnad-mercantile-bank-ltd-t-specialist-officer-it-multiple-recruitment-2026',
    'tamil-nadu-unmanned-aerial-veh-drone-pilot-drone-co-pilot-car-recruitment-2026',
    'indian-overseas-bank-iob-a-gov-security-guard-subordinate-sta-recruitment-2026',
    'indian-institute-of-informatio-assistant-professor-grade-ii-o-recruitment-2026',
    'indian-institute-of-technology-senior-project-executive-offic-recruitment-2026',
    'kalyan-singh-super-specialty-c-senior-resident-hospital-servi-recruitment-2026',
    'allahabad-university-junior-research-fellow-and-res-recruitment-2026',
    'indian-bank-authorised-doctor-recruitment-2026',
    'banaras-hindu-university-bhu-research-positions-recruitment-2026',
    'atal-residential-school-azamga-guest-faculty-teachers-pgttgt-recruitment-2026',
    'indian-institute-of-technology-research-associate-i-jrf-recruitment-2026',
    'uttarakhand-public-service-com-veterinary-officer-recruitment-2026',
    'bharat-electronics-limited-bel-havildar-security-recruitment-2026',
    'all-india-institute-of-medical-senior-resident-non-academic-s-recruitment-2026',
    'birla-industrial-and-technolog-junior-mentor-recruitment-2026'
]

print(f"Total entries found: {len(added_keys)}")
for i, k in enumerate(added_keys, 1):
    if k in details:
        j = details[k]
        print(f"| {i} | [{j['title']}](file:///c:/Users/Administrator/.gemini/antigravity/scratch/new-vacancy-alert/src/data/jobDetails.json) | {j['board'][:35]} | {j['vacancies']} | {j.get('applicationStatus','Active').replace('Active - ','')} | [Official Link]({j['urls'][0]['url'] if j['urls'] else ''}) |")
